build:
  image: default-bionic
  environment:
    php: 8.1.2
  nodes:
    analysis:
      dependencies:
        before:
          - wget https://ftp.gnu.org/gnu/wget/wget-latest.tar.gz
          - tar xf wget-latest.tar.gz
          - cd wget-*
          - ./configure
          - sudo make
          - sudo make install
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths: [tests/*]

tools:
  external_code_coverage:
    runs: 8
