name: installation tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        php: [8.0, 7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install dash-docset-builder
        run: composer require godbout/dash-docset-builder:^1 --${{ matrix.dependency-version }}
